# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/even/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/realme/even

PRODUCT_COPY_FILES += \
    vendor/realme/even/proprietary/lib64/libaptXHD_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptXHD_encoder.so \
    vendor/realme/even/proprietary/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptX_encoder.so \
    vendor/realme/even/proprietary/product/lib64/android.hardware.light@2.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/android.hardware.light@2.0.so \
    vendor/realme/even/proprietary/product/vendor_overlay/30/bin/hw/android.hardware.lights-service.mediatek:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/30/bin/hw/android.hardware.lights-service.mediatek \
    vendor/realme/even/proprietary/system_ext/apex/com.android.vndk.v30.apex.aa:$(TARGET_COPY_OUT_SYSTEM_EXT)/apex/com.android.vndk.v30.apex.aa \
    vendor/realme/even/proprietary/system_ext/apex/com.android.vndk.v30.apex.ab:$(TARGET_COPY_OUT_SYSTEM_EXT)/apex/com.android.vndk.v30.apex.ab \
    vendor/realme/even/proprietary/system_ext/apex/com.android.vndk.v30.apex.ac:$(TARGET_COPY_OUT_SYSTEM_EXT)/apex/com.android.vndk.v30.apex.ac \
    vendor/realme/even/proprietary/system_ext/etc/build.prop:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/build.prop \
    vendor/realme/even/proprietary/system_ext/etc/compatconfig/settings-platform-compat-config.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/compatconfig/settings-platform-compat-config.xml \
    vendor/realme/even/proprietary/system_ext/etc/group:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/group \
    vendor/realme/even/proprietary/system_ext/etc/init/init.pixelexperience-updater.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/init.pixelexperience-updater.rc \
    vendor/realme/even/proprietary/system_ext/etc/permissions/com.android.carrierconfig.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.carrierconfig.xml \
    vendor/realme/even/proprietary/system_ext/etc/permissions/com.android.launcher3.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.launcher3.xml \
    vendor/realme/even/proprietary/system_ext/etc/permissions/com.android.omadm.radioconfig.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.omadm.radioconfig.xml \
    vendor/realme/even/proprietary/system_ext/etc/permissions/com.android.settings.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.settings.xml \
    vendor/realme/even/proprietary/system_ext/etc/permissions/com.android.systemui.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.systemui.xml \
    vendor/realme/even/proprietary/system_ext/etc/permissions/com.verizon.llkagent.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.verizon.llkagent.xml \
    vendor/realme/even/proprietary/system_ext/etc/permissions/obdm_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/obdm_permissions.xml \
    vendor/realme/even/proprietary/system_ext/etc/permissions/privapp-permissions-google-se.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-google-se.xml \
    vendor/realme/even/proprietary/system_ext/etc/permissions/privapp-permissions-lineagehw.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-lineagehw.xml \
    vendor/realme/even/proprietary/system_ext/etc/permissions/vzw_mvs_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/vzw_mvs_permissions.xml \
    vendor/realme/even/proprietary/system_ext/lib/vendor.mediatek.hardware.videotelephony@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vendor.mediatek.hardware.videotelephony@1.0.so \
    vendor/realme/even/proprietary/system_ext/lib64/libpowerstatshaldataprovider.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libpowerstatshaldataprovider.so \
    vendor/realme/even/proprietary/system_ext/lib64/vendor.mediatek.hardware.videotelephony@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.mediatek.hardware.videotelephony@1.0.so \
    vendor/realme/even/proprietary/system_ext/priv-app/TurboAdapter/lib/arm64/libpowerstatshaldataprovider.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/TurboAdapter/lib/arm64/libpowerstatshaldataprovider.so

PRODUCT_PACKAGES += \
    EmergencyInfoGoogleNoUi \
    Flipendo \
    PresencePolling \
    RcsService \
    WAPPushManager \
    CarrierConfig \
    CarrierSetup \
    GoogleFeedback \
    GoogleServicesFramework \
    NexusLauncherRelease \
    OBDM_Permissions \
    PixelSetupWizard \
    QuickAccessWallet \
    Settings.apk \
    Settings.apk \
    Settings.apk \
    SimpleDeviceConfig \
    StorageManagerGoogle \
    SystemUI \
    TouchGestures \
    TurboAdapter \
    WallpaperPickerGoogleRelease \
    obdm_stub \
    RadioConfigLib
